<?php require 'header.phtml'; ?>

<h1>Acceso de Administrador</h1>

<form action="autenticar" method="POST">
    <div>
        <label>Usuario</label>
        <input type="text" name="usuario" required>
    </div>
    <div>
        <label>Contraseña</label>
        <input type="password" name="contraseña" required>
    </div>

    <?php if (isset($error)): ?>
        <div class="error">
            <?= $error ?>
        </div>
    <?php endif; ?>

    <button type="submit">Ingresar</button>
</form>

<?php require 'footer.phtml'; ?>